Support zend-expressive-router 2.0
zendframework/zend-expressive-zendrouter pull request #16
Opened 2017-01-09 17:47 UTC by weierophinney

Updated zend-expressive-router to 2.0.

Added `$options` argument based on new interface spec; `$options` passed to `generateUri()` are now passed to the underlying router in order to generate the final URI.

2017-01-09 18:14 UTC, Ocramius requested changes

2017-01-09 18:14 UTC, Ocramius commented on test/ZendRouterTest.php
> +    public function testUriGenerationMayUseOptions()
An additional test checking recursive merging is needed

2017-01-09 19:18 UTC, weierophinney commented on test/ZendRouterTest.php
> +    public function testUriGenerationMayUseOptions()
Not sure how to go about that, which may indicate that the recursive merging isn't necessary yet. Currently, the only options I could find to test were around the translator; all others are ignored currently, as they would require using the zend-http URI generation; this implementation takes care of the other options known to Segment routes (query string argument and fragment support).

I'll remove the `ArrayUtils::merge` usage for now, and instead use `array_replace_recursive()`.

2017-01-09 19:19 UTC, weierophinney commented on test/ZendRouterTest.php
> +    public function testUriGenerationMayUseOptions()
Sorry, meant to say I'll replace `array_replace_recursive` with `array_merge`.

2017-01-09 19:23 UTC, weierophinney commented on test/ZendRouterTest.php
> +    public function testUriGenerationMayUseOptions()
Fixed now!

2017-01-11 06:34 UTC, michaelmoussa approved these changes
LGTM 👍

2017-01-11 21:49 UTC, merged