Hotfix - import correct Exception namespace
zendframework/zend-expressive-zendrouter pull request #20
Opened 2017-01-25 22:41 UTC by webimpress

Import correct `Exception` namespace:

`Zend\Expressive\Exception` is not defined.
Correctly it should be: `Zend\Expressive\Router\Exception`.

2017-02-02 06:11 UTC, geerteltink requested changes

2017-02-02 06:11 UTC, xtreamwayz commented on src/ZendRouter.php
> +use Zend\Expressive\Router\Exception;
There is no `Zend\Expressive\Router\Exception` or `Zend\Expressive\Exception`?

2017-02-02 07:25 UTC, webimpress commented on src/ZendRouter.php
> +use Zend\Expressive\Router\Exception;
In line 121 we have: `Exception\RuntimeException`.
I just notice that there is `Zend\Expressive\Exception\RuntimeException` (in zend-expressive) but this library does not require zend-expressive, so this is why I think, we should have here `Zend\Expressive\Router\Exception` to use `RuntimeException` from `zend-expressive-router`. What do you think?

2017-02-03 16:56 UTC, xtreamwayz commented on src/ZendRouter.php
> +use Zend\Expressive\Router\Exception;
Ah, zend-router is a dependency and it has a [Zend\Expressive\Router\Exception\RuntimeException](https://github.com/webimpress/zend-expressive-router/blob/master/src/Exception/RuntimeException.php).

So your change is actually correct.

2017-02-03 16:56 UTC, geerteltink approved these changes

2017-03-01 22:52 UTC, merged