Add ConfigProvider
zendframework/zend-expressive-zendrouter pull request #34
Opened 2018-01-25 21:00 UTC by xtreamwayz

Adds ConfigProvider with basic configuration.

2018-01-26 00:13 UTC, michalbundyra requested changes

2018-01-26 00:13 UTC, webimpress commented on composer.json
> +            "config-provider": "Zend\\Expressive\\Router\\ConfigProvider"
Again, I would consider changing namespace

2018-01-26 00:13 UTC, webimpress commented on src/ConfigProvider.php
> + * @copyright Copyright (c) 2015-2018 Zend Technologies USA Inc. (https://www.zend.com)
only 2018 please for new files

2018-01-26 00:13 UTC, webimpress commented on src/ConfigProvider.php
> +
remove empty line before strict type declaration

2018-01-26 00:13 UTC, webimpress commented on src/ConfigProvider.php
> +            'factories' => [
`invokables` ?
https://github.com/zendframework/zend-expressive-skeleton/blob/release-3.0.0/src/ExpressiveInstaller/Resources/config/router-zend-router.php#L10

I would consider to have here `invokable` for `ZendRouter`, and `aliases` for `RouterInterface`.

2018-01-26 00:13 UTC, webimpress commented on test/ConfigProviderTest.php
> + * @copyright Copyright (c) 2015-2018 Zend Technologies USA Inc. (https://www.zend.com)
2018 only for new files, please

2018-01-26 00:13 UTC, webimpress commented on test/ConfigProviderTest.php
> +
no new line before strict_type declaration

2018-01-26 00:13 UTC, webimpress commented on test/ConfigProviderTest.php
> +        self::assertInternalType('array', $config);
`$this->`... ?

2018-01-26 00:13 UTC, webimpress commented on test/ConfigProviderTest.php
> +        self::assertArrayHasKey(RouterInterface::class, $config['dependencies']['factories']);
`$this->` ... 5x ?

2018-01-29 15:13 UTC, weierophinney commented
@xtreamwayz Same comments from the fastroute package apply here:

- Use a subnamespace for the `ConfigProvider`.
- Use `$this->` instead of `self::` for now.

2018-02-06 19:20 UTC, merged

2018-02-06 19:20 UTC, weierophinney commented
Thanks, @xtreamwayz!